config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  # delete '/articles/:article_id/likes/:id', to: 'likes#destroy' ,as: :like
  
  resources :articles do
    resources :likes, only: [:create, :destroy] 
  end

  resources :articles do
    resources :comments
  end

  resources :articles do
    resources :favorites, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  # resources :favorites, only: [:destroy]

  resources :searches, only: [:index, :show]
  # resource :sessions, only: [:new, :create, :destroy]

  resources :users
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :comment_content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article, counter_cache: :likes_count
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :articles, through: :favorites
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

    def set_search
      @q = Article.ransack(params[:q])
      @article = @q.result(distinct: true)
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]

  def index
    @articles = Article.order("created_at DESC").page(params[:page]).per(10)
    @articles ||= Post.page(params[:page]).per(10)
    # @user = current_user
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user 
    @article.title = params[:article][:title]
    @article.content = params[:article][:content]
    @article.save
    redirect_to root_path
  end 

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new #①
    @comments = @article.comments #②
    @like = Like.find_by(user_id: current_user.id, article_id: params[:id]) if user_signed_in?
    @favorite = Favorite.find_by(user_id: current_user.id, article_id: params[:id]) if user_signed_in?
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    article = Article.find(params[:id])
    article.update(article_params)
    redirect_to root_path
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id]) #①
    @comment = @article.comments.build(comment_params) #②
    @comment.user_id = current_user.id #③
    if @comment.save
      render :index #④
    end
  end

  def destroy
    @comment = Comment.find(params[:id]) #⑤
    if @comment.destroy
      render :index #⑥
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:comment_content, :article_id, :user_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @favorite = Favorite.create(user_id: current_user.id, article_id: params[:article_id])
    # @article.reload
  end

  def destroy
    @article = Article.find(params[:article_id])
    @favorite = Favorite.find_by(user_id: current_user.id, article_id: params[:article_id])
    @favorite.destroy
    # @article.reload
    
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    @article.reload
  end

  def destroy
    @article = Article.find(params[:article_id])
    @like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    @like.destroy
    @article.reload
  end

  def show
    @like = Like.find_by(user_id: current_user.id, article_id: params[:id]) if user_signed_in?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @q = Article.ransack(params[:q])
    @article = @q.result(distinct: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where("user_id = ?", @user)
    @articles = Article.where("user_id = ?",@user)
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/articles/edit.html.haml
= render 'shared/header'
.container
  .form-content
    = form_with model: @article, url: "/articles/#{@article.id}",local: true, method: :patch do |f|
      .form-title
        %lavel.title-lavel
          title
        = f.text_field :title, class: "post-title-content", placeholder: 'タイトルを入力してください'
      .main-content
        %lavel.content-lavel
          content
        = f.text_area :content, class: "post-main-content",  placeholder: '本文を入力してください'
      .post-btn
        = f.submit "send",class: "green-btn"
= render 'shared/footer'

app/views/articles/index.html.haml
.wrapper
  = render 'shared/header'
  .main
    .hoge
    .hoge2
      .item-title
        Articles
      .item-list-block
        - @articles.each do |article|
          .item-list.clearfix
            %a.item-list-image{ href: ''}
              %img{ alt: '', src: '', width: 'auto', height: 'auto'}
            .item-list-big
              .item-list-content
                = link_to article_path(article.id) do
                  = article.title
              .item-list-under
                %span.user1
                  by
                %a.user2
                  = link_to user_path(article.user.id) do
                    = article.user.name
                .time
                  = article.updated_at.strftime("%Y/%m/%d")
                .good-mark
                  .comment
                    .action
                  .good
                    .action
                      %i.fas.fa-thumbs-up 
                      %span
                        = article.likes_count
                  .stock
                    .action
                      -# = link_to "登録", add_article_path(article), method: :post 
      .pagination
        = paginate(@articles)
    .hoge3
  = render 'shared/footer'

app/views/articles/new.html.haml
= render 'shared/header'
= render 'shared/form'
= render 'shared/footer'

app/views/articles/show.html.haml
= render 'shared/header'
.container
  .comment-page-reputation
    .comment-good       
      %span{:id => "article-#{@article.id}-like"}
        = render 'shared/likes', article: @article, like: @like
    .comment-stock
      %span{:id => "article-#{@article.id}-favorite"}
        = render 'shared/favorites', article: @article, favorite: @favorite
    .comment-sns
      Twitter
  .comment-page-info
    .commnet-page-title
      = @article.title
    .comment-page-user
      = link_to user_path(@article.user.id) do
        = @article.user.name
    .comment-page-editbtn
      - if user_signed_in? && current_user.id == @article.user_id
        = link_to "Edit", edit_article_path(@article.id)
    .comment-page-delete
      - if user_signed_in? && current_user.id == @article.user_id
        = link_to "Delete", article_path, method: :delete
  .comment-page-content
    = simple_format(@article.content)    
  -# .comment-page-form-block
  -#   %input.comment-page-form
  -#   %input.comment-page-form-btn{ type: 'submit', name: '', value: 'Comment'}
  -# = render 'shared/footer'

  %div
  %h4 コメント
  #comments_area
    / #①
    / 投稿されたコメント一覧をブログの詳細ページに表示するためのrender
    = render partial: 'comments/index', locals: { comments: @comments }
  - if user_signed_in?
    / コメント入力欄をブログの詳細ページに表示するためのrender
    = render partial: 'comments/form', locals: { comment: @comment, article: @article }



-# = button_to "ストックする", add_article_path(@article), method: :post  