config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  # delete '/articles/:article_id/likes/:id', to: 'likes#destroy' ,as: :like
  
  resources :articles do
    resources :likes, only: [:create, :destroy] 
  end

  resources :articles do
    resources :comments
  end

  resources :articles do
    resources :favorites, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  # resources :favorites, only: [:destroy]

  resources :searches, only: [:index, :show]
  # resource :sessions, only: [:new, :create, :destroy]

  resources :users
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :articles, through: :favorites
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where("user_id = ?", @user)
    @articles = Article.where("user_id = ?",@user)
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.haml
= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f|
  %div= f.hidden_field :following_id
  = f.submit "Follow", class: "btn btn-large btn-primary follow-btn"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.followings.count
    following
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = @user.followers.count
    followers
    

app/views/users/_unfollow.html.haml
= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f|
  = f.submit "Unfollow", class: "btn btn-large follow-btn"

app/views/users/index.html.haml
= render 'shared/header'
%h1 ユーザー一覧
- @users.each do |user|
  -# = user.name
  %br/
  = link_to("#{user.name}さん", user_path(user.id) )
  %br/
  %br/

app/views/users/show.html.haml
= render 'shared/header'
.user-profile
  = @user.name
  - if user_signed_in? && current_user.id == @user.id
    = link_to "ログアウト", destroy_user_session_path, method: :delete
.tabs
  %input#all{:checked => "checked", :name => "tab_item", :type => "radio"}/
  %label.tab_item{:for => "all"} 
    %i.fas.fa-pencil-alt
  %input#programming{:name => "tab_item", :type => "radio"}/
  %label.tab_item{:for => "programming"}
    %i.fas.fa-folder-open
  %input#design{:name => "tab_item", :type => "radio"}/
  %label.tab_item{:for => "design"} 
    %i.fas.fa-users
  #all_content.tab_content
    - @articles.each_with_index do |article,i|
      .tab-content-nakami
        = link_to article_path(article.id) do
          = article.title
  #programming_content.tab_content
    - @user.articles.each_with_index do |article, i|
      .tab-content-nakami
        -# = link_to "削除", article_favorite_path(@favorites[i][:id]), method: :delete do
        = link_to article_path(article.id), class: "nakami-block" do
          = article.title
  #design_content.tab_content
    .tab-content-nakami
      = render 'follow_form'
      = render 'stats'
= render 'shared/footer'














-# 

-# = @user.name
-# %ul.tab
-#   %li.select 自分の記事
-#   %li ストック
-#   %li フォロー/アンフォロー
-#   -# %li タブ4
-# %ul.content
-#   %li
-#   %li.hide 
-#     - @user.articles.each_with_index do |article, i|
-#       = link_to "削除", favorite_path(@favorites[i][:id]), method: :delete
-#       = article.title
-#   %li.hide
-#     = render 'follow_form'
-#     = render 'stats'
-#   -# %li.hide 弱虫やーい。と囃し

app/views/users/show_follow.html.haml
- @user.followings.each do |user|
  %table
    %tr
      %td
        = user.name
      %td= link_to '詳細', user_path(user)

app/views/users/show_follower.html.haml
- @user.followers.each do |user|
  %table
    %tr
      %td
        = user.name
      %td= link_to '詳細', user_path(user)