config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  # delete '/articles/:article_id/likes/:id', to: 'likes#destroy' ,as: :like
  
  resources :articles do
    resources :likes, only: [:create, :destroy] 
  end

  resources :articles do
    resources :comments
  end

  resources :articles do
    resources :favorites, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  # resources :favorites, only: [:destroy]

  resources :searches, only: [:index, :show]
  # resource :sessions, only: [:new, :create, :destroy]

  resources :users
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :comment_content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article, counter_cache: :likes_count
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :articles, through: :favorites
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]

  def index
    @articles = Article.order("created_at DESC").page(params[:page]).per(10)
    @articles ||= Post.page(params[:page]).per(10)
    # @user = current_user
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user 
    @article.title = params[:article][:title]
    @article.content = params[:article][:content]
    @article.save
    redirect_to root_path
  end 

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new #①
    @comments = @article.comments #②
    @like = Like.find_by(user_id: current_user.id, article_id: params[:id]) if user_signed_in?
    @favorite = Favorite.find_by(user_id: current_user.id, article_id: params[:id]) if user_signed_in?
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    article = Article.find(params[:id])
    article.update(article_params)
    redirect_to root_path
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id]) #①
    @comment = @article.comments.build(comment_params) #②
    @comment.user_id = current_user.id #③
    if @comment.save
      render :index #④
    end
  end

  def destroy
    @comment = Comment.find(params[:id]) #⑤
    if @comment.destroy
      render :index #⑥
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:comment_content, :article_id, :user_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    @article.reload
  end

  def destroy
    @article = Article.find(params[:article_id])
    @like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    @like.destroy
    @article.reload
  end

  def show
    @like = Like.find_by(user_id: current_user.id, article_id: params[:id]) if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where("user_id = ?", @user)
    @articles = Article.where("user_id = ?",@user)
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.0.1/css/all.css", :rel => "stylesheet"}/
    %title PersonalApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    

app/views/shared/_favorites.html.haml
- if user_signed_in?
  - if article.favorite_user(current_user.id)
    = button_to article_favorite_path(article, favorite), method: :delete, remote: true do
      %i.fas.fa-check ストック済み
      -# %span
      -#   = article.likes_count
  - else
    = button_to article_favorites_path(article), remote: true do
      %i.fas.fa-folder-open
      -# %span
      -#   = article.likes_count
- else
  %i.fas.fa-folder-open
  %span
    -# = article.likes_count

app/views/shared/_footer.html.haml
.footer
    Created by yooooshiki

app/views/shared/_form.html.haml
.container
  .form-content
    = form_with model: @article, url: "/articles/", local: true, method: "post" do |f|
      .form-title
        %lavel.title-lavel
          title
        = f.text_field :title, class: "post-title-content", placeholder: 'タイトルを入力してください'
      .main-content
        %lavel.content-lavel
          content
        = f.text_area :content, class: "post-main-content",  placeholder: '本文を入力してください'
      .post-btn
        = f.submit "send",class: "green-btn"

app/views/shared/_header.html.haml
.header
  .header-light
    .appname 
      = link_to 'Wisdom Post', articles_path, class: 'btn-in'
    .search 
      = search_form_for @q, url: searches_path do |f| 
        = f.search_field :title_cont, placeholder: "検索ワード" 
  .header-right
    - if user_signed_in?
      .header-right-wrapper
        .stock
          = link_to 'Users', users_path, class: 'btn-in'
        .post
          = link_to 'Post', new_article_path, class: 'btn-in'
          
        .mypage
          = link_to 'Mypage', "/users/#{current_user.id}", class: 'btn-in'
    - else 
      .header-right-wrapper
        .login-btn
          = link_to 'Login', new_user_session_path, class: 'btn-in'
        .sign-up-btn
          =link_to 'Sign-up', new_user_registration_path, class: 'btn-in'
          
      

app/views/shared/_likes.html.haml
- if user_signed_in?
  - if article.like_user(current_user.id)
    = button_to article_like_path(article, like), method: :delete, remote: true do
      %i.fas.fa-check いいね済み
      -# %span
      -#   = article.likes_count
  - else
    = button_to article_likes_path(article), remote: true do
      %i.fas.fa-thumbs-up
      -# %span
      -#   = article.likes_count
- else
  %i.fas.fa-thumbs-up
  %span
    = article.likes_count